# Messaging Platform
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  namespace: default
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release2
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  namespace: default
spec:
  selector:
    app: queue
  ports:
    - name: http
      port: 80
      targetPort: 8161
    - name: endpoint
      port: 61616   
  type: LoadBalancer